print("Welcome to the Band Name Generator.")
city = input("What's the name of the city you grew up in?\n")
pet = input("What is you pet's name?\n")
print("Your band name could be " + city + " " + pet)
print("Or you band name could be " + pet + " " + city)